# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dindr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # React and Yoga Pods
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
    ]

  # Required by RNFirebase
    pod 'Firebase/Core'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
    pod 'Firebase/AdMob'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Crash'
    pod 'Firebase/Database'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Storage'

  

  target 'dindrTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'dindr-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dindr-tvOS

  target 'dindr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
